In [43]:
import numpy as np
import pandas as pd
import plotly.express as px

In [44]:
df = pd.read_csv('Salary_dataset.csv', index_col= 0)
df.head()

,YearsExperience,Salary
0,1.2,39344.0
1,1.4,46206.0
2,1.6,37732.0
3,2.1,43526.0
4,2.3,39892.0


In [45]:
x_bar = df.YearsExperience.mean()
y_bar = df.Salary.mean()

theta_1 = sum( (df.YearsExperience - x_bar) * (df.Salary - y_bar) ) / sum((df.YearsExperience - x_bar) ** 2)
theta_0 = y_bar - (theta_1 * x_bar)

print(theta_0, theta_1)

24848.203966523193 9449.962321455077


In [46]:
from sklearn.linear_model import LinearRegression

le = LinearRegression()

le.fit(df[['YearsExperience']], df['Salary'])

LinearRegression()

In [47]:
le.intercept_

24848.203966523208

In [48]:
le.coef_

array([9449.96232146])

In [49]:
df[['YearsExperience']].ndim

2

In [50]:
np.array([[3.4]]).ndim

2

In [51]:
le.predict(np.array([[3.4]]))

c:\Users\hp\.conda\envs\ML\lib\site-packages\sklearn\base.py:493: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([56978.07585947])

In [52]:
salary_predicted_ols = le.predict(df[['YearsExperience']])

In [53]:
df['salary_predicted_ols'] = salary_predicted_ols

In [54]:
df.head()

,YearsExperience,Salary,salary_predicted_ols
0,1.2,39344.0,36188.158752
1,1.4,46206.0,38078.151217
2,1.6,37732.0,39968.143681
3,2.1,43526.0,44693.124842
4,2.3,39892.0,46583.117306


In [55]:
px.scatter(data_frame= df, x= 'YearsExperience', y= 'Salary', trendline= 'ols', trendline_color_override= 'red')

In [56]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor()

sgd.fit(df[['YearsExperience']], df['Salary'])

SGDRegressor()

In [57]:
sgd.eta0

0.01

In [58]:
sgd.early_stopping

False

In [59]:
salary_predicted_sgd = sgd.predict(df[['YearsExperience']])
salary_predicted_sgd

array([ 29256.01544027,  31361.16560467,  33466.31576907,  38729.19118006,
        40834.34134445,  48202.36691984,  49254.94200204,  51360.09216644,
        51360.09216644,  56622.96757743,  58728.11774183,  59780.69282402,
        59780.69282402,  60833.26790622,  65043.56823502,  69253.86856381,
        71359.01872821,  73464.1688926 ,  79779.61938579,  80832.19446799,
        89252.79512558,  92410.52037217, 100831.12102976, 103988.84627635,
       109251.72168735, 112409.44693394, 117672.32234493, 118724.89742713,
       126092.92300252, 128198.07316692])

In [60]:
df['salary_predicted_sgd'] = salary_predicted_sgd

In [61]:
df

,YearsExperience,Salary,salary_predicted_ols,salary_predicted_sgd
0,1.2,39344.0,36188.158752,29256.015440
1,1.4,46206.0,38078.151217,31361.165605
2,1.6,37732.0,39968.143681,33466.315769
3,2.1,43526.0,44693.124842,38729.191180
4,2.3,39892.0,46583.117306,40834.341344
5,3.0,56643.0,53198.090931,48202.366920
6,3.1,60151.0,54143.087163,49254.942002
7,3.3,54446.0,56033.079627,51360.092166
8,3.3,64446.0,56033.079627,51360.092166
9,3.8,57190.0,60758.060788,56622.967577


In [62]:
df.shape

(30, 4)