# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [23]:
import numpy as np

### 1.1) Indexing a 1D array (Vectors)

In [2]:
vec = np.array([4, 5, 2, 3])
print(vec[0])
print(vec[1])
print(vec[-1])

4
5
3


### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [10]:
matrix = np.array([[4, 5, 2, 3],
                   [1, 7, 8, 0],
                   [9, 6, 4, 2]])
matrix

array([[4, 5, 2, 3],
       [1, 7, 8, 0],
       [9, 6, 4, 2]])

In [11]:
matrix[1, 3]

np.int64(0)

In [12]:
matrix[1][-1]

np.int64(0)

In [13]:
testmx = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(testmx[1:, 1:3])

[[5 6]
 [8 9]]


### Slicing

In [14]:
matrix

array([[4, 5, 2, 3],
       [1, 7, 8, 0],
       [9, 6, 4, 2]])

In [15]:
matrix[0:1, 0:2]

array([[4, 5]])

In [16]:
matrix[1:, 1:3]

array([[7, 8],
       [6, 4]])

### 1.3) Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [17]:
big_matrix = np.array([[4, 5, 2, 3],
                       [1, 7, 8, 0],
                       [9, 6, 4, 2],
                       [20, 21, 19, 5],
                       [90, 60, 40, 32]])

big_matrix

array([[ 4,  5,  2,  3],
       [ 1,  7,  8,  0],
       [ 9,  6,  4,  2],
       [20, 21, 19,  5],
       [90, 60, 40, 32]])

In [18]:
big_matrix[ [0, 2, 4], :]

array([[ 4,  5,  2,  3],
       [ 9,  6,  4,  2],
       [90, 60, 40, 32]])

In [22]:
print(big_matrix)

big_matrix[[4,0],[3,2]]

[[ 4  5  2  3]
 [ 1  7  8  0]
 [ 9  6  4  2]
 [20 21 19  5]
 [90 60 40 32]]


array([32,  2])

# Great Job!
