# NumPy Operations


* 1) Arithmetic and Logic
    - 1.1) Arithmetic
    - 1.2) Logic
* 2) Universal Array Functions
    - 2.1) max, min, average, sum
    - 2.2) power, sqrt, exp, log
    - 2.3) sin, cos, tan
    - 2.4) dot product

## 1) Arithmetic and Logic

You can easily perform array with array arithmetic, or scalar with array arithmetic. <br>
You can also perform logic operation on array. <br>

**Broadcasting**: a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.

Let's see some examples:

In [1]:
import numpy as np

### 1.1) Arithmetic

In [ ]:
# concate two lists will reture a list have all the elements of both lists
l1 = [1, 2, 3, 4, 5]
l2 = [7, 8, 9, 10, 11]
l1 + l2 # [1, 2, 3, 4, 5, 7, 8, 9, 10, 11]
# zip two lists will return a list of tuples, each tuple contains one element from each list
l3 = []
for n1, n2 in zip(l1, l2):
    l3.append(n1 + n2)

l3

[8, 10, 12, 14, 16]

In [7]:
# concat two numpy arrays will return a new array with summation of each element of both arrays
l1_arr = np.array([1, 2, 3, 4, 5])
l2_arr = np.array([7, 8, 9, 10, 11])
l1_arr + l2_arr

array([ 8, 10, 12, 14, 16])

In [8]:
# divide any number by 0 will return ZeroDivisionError
try :
    4 / 0
except ZeroDivisionError as e:
    print(" this is a ZeroDivisionError")

 this is a ZeroDivisionError


In [7]:
0 / 0

ZeroDivisionError: division by zero

In [11]:
# Warning on division by zero, but not an error!
# Just replaced with nan

arr = np.array([0, 2, 3, 4, 5])
print(l2_arr, "/", arr)
l2_arr / arr

[ 7  8  9 10 11] / [0 2 3 4 5]


/tmp/ipykernel_104735/2619605318.py:6: RuntimeWarning: divide by zero encountered in divide
  l2_arr / arr


array([inf, 4. , 3. , 2.5, 2.2])

In [12]:
arr = np.array([0, 2, 3, 4, 5])
arr_0 = np.array([0, 5, 7, 8, 9])
arr_0 / arr

/tmp/ipykernel_104735/1200048082.py:3: RuntimeWarning: invalid value encountered in divide
  arr_0 / arr


array([       nan, 2.5       , 2.33333333, 2.        , 1.8       ])

### 2.2) Comparison Operations

In [18]:
arr > 0

array([False,  True,  True,  True,  True])

**We can also do operations on 2-D arrays**

In [20]:
4 > 3

True

In [19]:
matrix = np.array([[4, 5, 2, 3],
                    [4, 5, 2, 3],
                    [4, 5, 2, 3]])
matrix > 3

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

## 2) Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

### 2.1) max, min, average, sum

**max**

In [21]:
arr.max()

5

In [22]:
np.max(arr)

5

**min**

In [23]:
np.min(arr)

0

**average**

In [25]:
arr

array([0, 2, 3, 4, 5])

In [24]:
np.average(arr)

2.8

**sum**

In [26]:
np.sum(arr)

14

### 2.2) sqrt, exp, log, sin

**power**

In [27]:
arr

array([0, 2, 3, 4, 5])

In [31]:
np.power(arr, 2)

array([ 0,  4,  9, 16, 25], dtype=int32)

**sqrt**

In [29]:
np.sqrt(arr)

array([0.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

**exp**

In [32]:
np.exp(arr)

array([  1.        ,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

**log**

In [33]:
np.log(arr)

C:\Users\hp\AppData\Local\Temp\ipykernel_32396\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### 2.3) sin, cos, tan

**sin**

In [34]:
np.sin(arr)

array([ 0.        ,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

**cos**

In [35]:
np.cos(arr)

array([ 1.        , -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

**tan**

In [36]:
np.tan(arr)

array([ 0.        , -2.18503986, -0.14254654,  1.15782128, -3.38051501])

### 2.4) dot product

In [43]:
matrix * matrix

array([[16, 25,  4,  9],
       [16, 25,  4,  9],
       [16, 25,  4,  9]])

In [45]:
arr_1 = np.array([ [1, 3, 5] ,[2, 4, 6] ])
arr_2 = np.array([ [2, 4] , [5, 6], [3, 1] ])

np.matmul(arr_1, arr_2)

array([[32, 27],
       [42, 38]])

In [13]:
arr_1 = np.array([ [1, 3, 5, 3] ,[2, 4, 6, 4] ])
arr_2 = np.array([ [2, 4] , [5, 6], [3, 1] ])

np.matmul(arr_1, arr_2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

# Great Job!

That's all we need to know for now!