In [1]:
import numpy as np

##### 1.4 Write a NumPy program to Sum the elements for a given array.

In [2]:
X = np.array([1, 7, 13, 105])

X.sum()

np.int64(126)

In [3]:
np.sum(X)

np.int64(126)

##### 1.4 Write a NumPy program to get the average of the elements for a given array.

In [4]:
X = np.array([1, 7, 13, 105])

np.average(X)

np.float64(31.5)

##### 1.5 Write a NumPy program to check for NaN of a given array.

In [5]:
a = np.array([1, 0, np.nan, np.nan])

np.isnan(a)

array([False, False,  True,  True])

##### 1.6 Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

##### 3.4 Write a NumPy program to get the powers of an array values element-wise.

In [9]:
np.power(X, 2)

array([    1,    49,   169, 11025])